// A block is a paragraph, or a list when it is an array of items.
export type LegalBlock = string | readonly string[];

export type LegalSection = { title: string; blocks: readonly LegalBlock[] };

export type LegalDocument = {
  title: string;
  intro: string;
  sections: readonly LegalSection[];
};

// Who answers for Feudo under LGPD (art. 9, III and art. 41): both documents
// print these through {controller} and {contact}.
export const LEGAL_CONTROLLER = "Fernando Lisboa";
export const LEGAL_CONTACT_EMAIL = "feudo@miolos.app";

const en = {
  versionLine: "In force since {date} (version {version})",
  otherDocument: { terms: "Read the privacy policy", privacy: "Read the terms of use" },
  back: "Back to Feudo",
  terms: {
    title: "Terms of use",
    intro:
      "These terms apply to everyone who uses Feudo. By creating your sign-up, or by accepting a new version, you agree to them and to the privacy policy.",
    sections: [
      {
        title: "What Feudo is",
        blocks: [
          "Feudo is a free app to organize a household's finances. It reads the accounts each person connects through Meu Pluggy, shows balances, transactions and categories, calculates the emergency reserve target, compares where to keep it and compares banks.",
          "Feudo is developed and maintained by {controller}, an individual, who answers for it under these terms.",
        ],
      },
      {
        title: "Your sign-up",
        blocks: [
          "To use Feudo you must be 18 or older and have your own email address, which is confirmed before your first sign-in. Your sign-up is personal: do not share your password or the sign-in links we email you.",
          "While Feudo is in testing, new sign-ups may require an invite.",
        ],
      },
      {
        title: "Households and members",
        blocks: [
          "A household brings together the people who share their finances. Whoever creates a household is its owner and can invite people by email, as admin or member; an invite is valid for 24 hours. The owner and the admins manage the household's people and settings; only the owner can transfer ownership or delete the household.",
          "Every member of a household sees the accounts assigned to it, with their balances and transactions, everything calculated from them, and the other members' names and emails. Invite only people you trust.",
          "You can leave a household whenever you want. When you leave, the accounts you connected leave with you.",
        ],
      },
      {
        title: "Bank connections",
        blocks: [
          "Feudo does not access your banks directly. You connect your banks in Meu Pluggy, a Pluggy service with its own terms, and give Feudo the credentials of an application of yours in the Pluggy Dashboard. With them Feudo only reads data: it does not move money, does not make payments and does not see your bank password.",
          "Before each connection you accept a consent text that says exactly what is read and who sees it. You can remove your credentials or delete a connection at any time.",
          "The data comes from the banks, through Meu Pluggy. Feudo shows what it receives and does not guarantee it is complete or up to date: when a bank or Meu Pluggy fails, the sync fails or runs late too.",
        ],
      },
      {
        title: "Not investment advice",
        blocks: [
          "Feudo's figures (reserve target, real yield, where to put the next reais, bank scores) are calculations made from your data and from public data. The analyst reading is a text generated by artificial intelligence, an Anthropic model, from those figures.",
          "All of it is informational. It is not a recommendation, advice or securities analysis, and it does not replace a licensed professional. The calculations and the text may contain errors or be out of date: check before you decide. Decisions about your money are yours.",
        ],
      },
      {
        title: "Acceptable use",
        blocks: [
          "You agree to connect only accounts that are yours or that you are authorized to connect, not to try to access other people's or other households' data, not to get around the usage limits (such as those on manual syncs, analyst readings and data downloads) and not to use Feudo for anything unlawful.",
          "A sign-up that breaks these terms may be suspended or deleted, with notice by email whenever possible.",
        ],
      },
      {
        title: "A free service, with no guarantee of continuous operation",
        blocks: [
          "Feudo is free and provided as is. We do our best to keep it running, correct and secure, but we do not guarantee it works without interruption. Features may change or be discontinued.",
          "If Feudo is shut down, we will tell you by email at least 30 days in advance, so you can download your data.",
          "To the extent the law allows, we are not liable for decisions made on the basis of the app's information, nor for failures of Pluggy, the banks or the other services named in the privacy policy. Nothing in these terms limits the rights the Consumer Defense Code (Código de Defesa do Consumidor) and the LGPD give you.",
        ],
      },
      {
        title: "Your data",
        blocks: [
          "How we handle your personal data is in the privacy policy, which is part of these terms. In Preferences you can download your data and delete your sign-up whenever you want.",
        ],
      },
      {
        title: "Deleting your sign-up or a household",
        blocks: [
          "Delete my sign-up, in Preferences, signs you out of every device and destroys your Meu Pluggy credentials at once. For 7 days you can cancel by signing in again; after that your sign-up, your connections and their transactions are erased from every household.",
          "A household's owner can delete it in Household. It disappears for everyone at once and the owner can restore it for 7 days; after that it is erased, and the accounts that were in it are left without a household, with whoever connected them.",
        ],
      },
      {
        title: "Changes to these terms",
        blocks: [
          "When these terms or the privacy policy change, we publish the new version on this page, with its date. To keep using Feudo you will need to accept it the next time you sign in; if you do not agree, you can still download your data and delete your sign-up.",
        ],
      },
      {
        title: "Governing law and venue",
        blocks: [
          "These terms are governed by Brazilian law. Any dispute about them may be settled in the courts of your place of residence.",
        ],
      },
      {
        title: "Contact",
        blocks: ["Questions about these terms: {contact}."],
      },
    ],
  },
  privacy: {
    title: "Privacy policy",
    intro:
      "This policy explains which personal data Feudo processes, what for, who it is shared with, how long it is kept and how you exercise your rights under Brazil's General Data Protection Law (LGPD, Law 13,709/2018).",
    sections: [
      {
        title: "Who the controller is",
        blocks: [
          "The controller of your data is {controller}, an individual who develops and maintains Feudo. For any privacy matter, including exercising your rights, write to {contact}. This is also the channel of the person in charge of personal data processing (encarregado).",
        ],
      },
      {
        title: "What we keep and why",
        blocks: [
          [
            "Sign-up: name, email, password (kept only as a hash, never as text), your sign-in sessions (with each one's IP address and browser) and the version and date on which you accepted these documents. They let you sign in, receive invites and notices, and prove your acceptance.",
            "Preferences: theme, tutorials already seen and whether they start on their own.",
            "Households: name, members and roles, invites (with the invited person's email), time zone and how many months of fixed cost the reserve should cover.",
            "Meu Pluggy credentials: client id and client secret, kept encrypted and never shown again. They are used only to read your banks.",
            "Consent: for each connection, the date, the version and the exact text you accepted.",
            "Connections, accounts and investments: bank, Item ID, type, account name, balance, rate, maturity, label (individual or household) and the date of the last sync.",
            "Transactions: date, amount, description, the category the bank reports and whether it is money in or out. The CPF or CNPJ of the account holder and of the other party of a transaction is kept only as an irreversible code, computed with a secret key, to tell your accounts apart and to recognize transfers between people in the household. Feudo has no field for the other party's name, but the description the bank sends may contain it.",
            "Annotations: categorizations, rules, internal-transfer marks, reserve adjustments and bank-comparison weights, with who made them and when.",
            "Analyst readings: the figures sent to the model, the text of the answer, the version of the instructions, the model used and who asked.",
            "Access log: who opened Overview, Transactions, Categories or Reserve, or downloaded their data, in which household and when, without any amounts. You see your own entries in Household, under Your recent access.",
            "Usage controls: attempts to authenticate with Meu Pluggy and manual syncs, to enforce the limits.",
            "Hosting technical logs, without credentials, documents, amounts or descriptions.",
          ],
          "Feudo does not ask for your CPF, does not keep your bank password, and does not sell your data or use it for advertising.",
        ],
      },
      {
        title: "Legal bases",
        blocks: [
          [
            "Performance of the contract (art. 7, V): sign-up, households, preferences and the service's emails.",
            "Consent (art. 7, I): reading your banks and everything that comes from it: credentials, accounts, transactions, annotations, calculations and the analyst reading. You can withdraw it whenever you want, as Your rights explains.",
            "Legitimate interest (art. 7, IX): access log, usage controls and technical logs, to protect your data, prevent abuse and investigate incidents.",
          ],
        ],
      },
      {
        title: "Who we share it with",
        blocks: [
          "Your data is not sold. The services below receive personal data so that Feudo works:",
          [
            "Pluggy (Brazil): receives your application's credentials at every sync and returns the data of the banks you connected in Meu Pluggy. Your Meu Pluggy account follows Pluggy's terms.",
            "Anthropic (United States): to write the analyst reading, receives only the figures Feudo calculated for the household (totals, rates, reserve target and positions, bank comparison) and the names of the institutions; never transactions, descriptions, account names, documents or credentials.",
            "Vercel (United States): hosts the app and keeps the technical logs.",
            "Neon (United States): hosts the database where all of this is kept.",
            "Resend (United States): sends Feudo's emails (confirmation, sign-in link, password reset, invites and deletion notices) and receives each message's address and content.",
            "Household members: see your name and email, the accounts in the household with their balances and transactions, and what is calculated from them. Nobody but you sees your credentials or manages your connections.",
          ],
          "The CDI, Selic and IPCA indices come from the Central Bank (SGS); no data of yours is sent in that request.",
          "We may also share data when the law or a court order requires it.",
        ],
      },
      {
        title: "International transfer",
        blocks: [
          "Anthropic, Vercel, Neon and Resend are in the United States, so your data is transferred outside Brazil (LGPD art. 33). These companies process the data on Feudo's behalf, under the contracts and data-protection safeguards they offer their customers.",
        ],
      },
      {
        title: "How long we keep it",
        blocks: [
          [
            "Sign-up, preferences and acceptance: until your sign-up is deleted.",
            "Meu Pluggy credentials: until you remove them or ask to delete your sign-up; in both cases they are destroyed at once.",
            "Connections, accounts and transactions: until you delete the connection or your sign-up. If the household is deleted, or you leave it, the accounts are left without a household, visible only to you, until you move them.",
            "Consent: as long as the connection it authorized exists. A consent accepted without the connection being created is erased after 24 hours.",
            "Household data (settings, annotations, targets and analyst readings): until the household is deleted. Categorizations and marks follow their transaction and are erased with it.",
            "Access log: 12 months. If you delete your sign-up, the entries stay until they complete 12 months, without identifying you; if the household is deleted, its entries are erased.",
            "Invites: valid for 24 hours; expired or cancelled ones are erased every day.",
            "Sign-in, confirmation and password-reset links: until they expire; expired ones are erased every day.",
            "Usage controls: Meu Pluggy authentication attempts, 15 minutes; manual syncs, 48 hours.",
            "Technical logs: Vercel's default period.",
          ],
          "Deleting your sign-up or a household comes with 7 days to change your mind; after that, the data is erased for good.",
        ],
      },
      {
        title: "Your rights",
        blocks: [
          [
            "Confirmation and access: in Preferences, Download my data produces a file with your data: sign-up (with your sign-in sessions and the acceptance of these documents), preferences and tutorials, the households you belong to and your role in each, your Meu Pluggy credentials (dates only, never the secret), consents, connections, accounts, investments, transactions, the annotations you made and your access log. It does not include data that belongs to the whole household (settings, invites, analyst readings) or short-lived usage controls; ask for them at {contact}. You can download it up to 3 times every 24 hours, and each download shows in the access log. The download needs an active household; if you are in none, write to {contact} and we will send you the file.",
            "Portability: the same file, in an open format (JSON) that another service can read.",
            "Correction: what comes from the bank is corrected at the bank and arrives with the next sync; to correct your name or email, write to {contact}.",
            "Withdrawing consent: in Your connections, removing your credentials stops the sync and destroys them at once, and deleting a connection erases its accounts with their transactions. Revoking Feudo's access in Meu Pluggy only stops future syncs: what was already read stays here until you delete your connections.",
            "Erasure: Delete my sign-up, in Preferences, as described in How long we keep it.",
            "Information about sharing: Who we share it with lists everyone who receives your data.",
            "Complaint: you can complain to the National Data Protection Authority (ANPD).",
          ],
          "Requests by email are answered within 15 days.",
        ],
      },
      {
        title: "Security",
        blocks: [
          "Passwords kept only as a hash; Meu Pluggy credentials encrypted with AES-256-GCM, with a key kept outside the database; CPF and CNPJ kept as a code made with another secret key; connections always over HTTPS; attempt limits on sign-in, bank connection, sync and analyst readings; and automated tests that check, on every change, that one household cannot read another's data.",
          "If a security incident happens that may bring you relevant risk or harm, we will tell you and the ANPD, as the law requires.",
        ],
      },
      {
        title: "Cookies and data on your device",
        blocks: [
          "Feudo uses only necessary cookies: the session cookies that keep you signed in, and one that remembers whether the sidebar is collapsed. There are no advertising or analytics cookies.",
          "Because Feudo can be installed as an app, your browser keeps on the device a copy of the screens you opened in the last 24 hours, to show them without internet. That copy stays on the device only and is erased when you sign out, switch household or ask to delete your sign-up; to erase it sooner, clear the site's data in your browser settings.",
        ],
      },
      {
        title: "Children and teenagers",
        blocks: ["Feudo is not meant for people under 18 and must not be used by them."],
      },
      {
        title: "Changes to this policy",
        blocks: [
          "When this policy changes, we publish the new version on this page, with its date, and ask for your acceptance the next time you sign in.",
        ],
      },
    ],
  },
};

const ptBR = {
  versionLine: "Em vigor desde {date} (versão {version})",
  otherDocument: { terms: "Ler a política de privacidade", privacy: "Ler os termos de uso" },
  back: "Voltar ao Feudo",
  terms: {
    title: "Termos de uso",
    intro:
      "Estes termos valem para todos que usam o Feudo. Ao criar seu cadastro, ou ao aceitar uma versão nova, você concorda com eles e com a política de privacidade.",
    sections: [
      {
        title: "O que é o Feudo",
        blocks: [
          "O Feudo é um aplicativo gratuito para organizar as finanças de uma casa. Ele lê as contas que cada pessoa conecta pelo Meu Pluggy, mostra saldos, transações e categorias, calcula a meta da reserva de emergência, compara onde guardá-la e compara bancos.",
          "O Feudo é desenvolvido e mantido por {controller}, pessoa física, que responde por ele nestes termos.",
        ],
      },
      {
        title: "Seu cadastro",
        blocks: [
          "Para usar o Feudo, você precisa ter 18 anos ou mais e um e-mail seu, que é confirmado antes do primeiro acesso. O cadastro é pessoal: não compartilhe sua senha nem os links de entrada que enviamos por e-mail.",
          "Enquanto o Feudo estiver em fase de testes, novos cadastros podem depender de convite.",
        ],
      },
      {
        title: "Casas e membros",
        blocks: [
          "Uma casa reúne as pessoas que dividem as finanças. Quem cria a casa é o responsável por ela e pode convidar pessoas por e-mail, como administrador ou membro; o convite vale por 24 horas. O responsável e os administradores cuidam das pessoas e das configurações da casa; só o responsável pode transferir a responsabilidade ou excluir a casa.",
          "Todos os membros de uma casa veem as contas que estão nela, com saldos e transações, tudo o que é calculado a partir delas e o nome e o e-mail dos outros membros. Convide só pessoas em quem você confia.",
          "Você pode sair de uma casa quando quiser. Ao sair, as contas que você conectou saem com você.",
        ],
      },
      {
        title: "Conexões bancárias",
        blocks: [
          "O Feudo não acessa seus bancos diretamente. Você conecta seus bancos no Meu Pluggy, um serviço da Pluggy com termos próprios, e informa ao Feudo as credenciais de uma aplicação sua no Pluggy Dashboard. Com elas, o Feudo só lê dados: não movimenta dinheiro, não faz pagamentos e não vê a senha do seu banco.",
          "Antes de cada conexão, você aceita um texto de consentimento que diz exatamente o que é lido e quem vê. Você pode remover suas credenciais ou excluir uma conexão a qualquer momento.",
          "Os dados vêm dos bancos, por meio do Meu Pluggy. O Feudo mostra o que recebe e não garante que esteja completo ou atualizado: quando o banco ou o Meu Pluggy falham, a sincronização também falha ou atrasa.",
        ],
      },
      {
        title: "Não é recomendação de investimento",
        blocks: [
          "Os números do Feudo (meta da reserva, rendimento real, onde colocar os próximos reais, notas dos bancos) são cálculos feitos a partir dos seus dados e de dados públicos. A leitura do analista é um texto gerado por inteligência artificial, um modelo da Anthropic, a partir desses números.",
          "Tudo isso é informativo. Não é recomendação, consultoria nem análise de valores mobiliários, e não substitui um profissional habilitado. Os cálculos e o texto podem ter erros ou estar desatualizados: confira antes de decidir. As decisões sobre o seu dinheiro são suas.",
        ],
      },
      {
        title: "Uso permitido",
        blocks: [
          "Você se compromete a conectar só contas suas ou que tenha autorização para conectar, a não tentar acessar dados de outras pessoas ou de outras casas, a não contornar os limites de uso (como os de sincronização manual, leituras do analista e downloads de dados) e a não usar o Feudo para nada ilegal.",
          "Um cadastro que viole estes termos pode ser suspenso ou excluído, com aviso por e-mail sempre que possível.",
        ],
      },
      {
        title: "Serviço gratuito, sem garantia de funcionamento contínuo",
        blocks: [
          "O Feudo é gratuito e oferecido como está. Fazemos o possível para mantê-lo no ar, correto e seguro, mas não garantimos que funcione sem interrupções. Funcionalidades podem mudar ou deixar de existir.",
          "Se o Feudo for encerrado, avisaremos por e-mail com pelo menos 30 dias de antecedência, para que você possa baixar seus dados.",
          "Na medida em que a lei permite, não respondemos por decisões tomadas com base nas informações do aplicativo nem por falhas da Pluggy, dos bancos ou dos outros serviços citados na política de privacidade. Nada nestes termos limita os direitos que o Código de Defesa do Consumidor e a LGPD garantem a você.",
        ],
      },
      {
        title: "Seus dados",
        blocks: [
          "Como tratamos seus dados pessoais está na política de privacidade, que faz parte destes termos. Em Preferências, você pode baixar seus dados e excluir seu cadastro quando quiser.",
        ],
      },
      {
        title: "Excluir seu cadastro ou uma casa",
        blocks: [
          "Excluir meu cadastro, em Preferências, encerra sua sessão em todos os aparelhos e destrói suas credenciais do Meu Pluggy na hora. Por 7 dias, você pode cancelar entrando de novo; depois disso, seu cadastro, suas conexões e as transações delas são apagados de todas as casas.",
          "O responsável por uma casa pode excluí-la em Casa. Ela some para todos na hora e pode ser restaurada pelo responsável por 7 dias; depois disso, é apagada, e as contas que estavam nela ficam sem casa, com quem as conectou.",
        ],
      },
      {
        title: "Mudanças nestes termos",
        blocks: [
          "Quando estes termos ou a política de privacidade mudarem, publicamos a versão nova nesta página, com a data. Para continuar usando o Feudo, você precisará aceitá-la no próximo acesso; se não concordar, ainda poderá baixar seus dados e excluir seu cadastro.",
        ],
      },
      {
        title: "Lei aplicável e foro",
        blocks: [
          "Estes termos seguem as leis do Brasil. Qualquer questão sobre eles pode ser resolvida no foro do seu domicílio.",
        ],
      },
      {
        title: "Contato",
        blocks: ["Dúvidas sobre estes termos: {contact}."],
      },
    ],
  },
  privacy: {
    title: "Política de privacidade",
    intro:
      "Esta política explica que dados pessoais o Feudo trata, para quê, com quem são compartilhados, por quanto tempo ficam guardados e como você exerce seus direitos pela Lei Geral de Proteção de Dados (LGPD, Lei 13.709/2018).",
    sections: [
      {
        title: "Quem é o controlador",
        blocks: [
          "O controlador dos seus dados é {controller}, pessoa física que desenvolve e mantém o Feudo. Para qualquer assunto de privacidade, inclusive para exercer seus direitos, escreva para {contact}. Esse é também o canal do encarregado pelo tratamento de dados pessoais.",
        ],
      },
      {
        title: "Que dados guardamos e para quê",
        blocks: [
          [
            "Cadastro: nome, e-mail, senha (guardada só como hash, nunca como texto), suas sessões de acesso (com o endereço IP e o navegador de cada uma) e a versão e a data em que você aceitou estes documentos. Servem para você entrar, receber convites e avisos e provar seu aceite.",
            "Preferências: tema, tutoriais já vistos e se eles começam sozinhos.",
            "Casas: nome, membros e papéis, convites (com o e-mail de quem foi convidado), fuso horário e quantos meses de custo fixo a reserva deve cobrir.",
            "Credenciais do Meu Pluggy: client id e client secret, guardados criptografados e nunca exibidos de novo. Servem só para ler os seus bancos.",
            "Consentimento: para cada conexão, a data, a versão e o texto exato que você aceitou.",
            "Conexões, contas e investimentos: banco, Item ID, tipo, nome da conta, saldo, taxa, vencimento, rótulo (individual ou da casa) e a data da última sincronização.",
            "Transações: data, valor, descrição, a categoria informada pelo banco e se é entrada ou saída. O CPF ou CNPJ do titular da conta e da outra parte de uma transação é guardado só como um código irreversível, calculado com uma chave secreta, para distinguir suas contas e reconhecer transferências entre pessoas da casa. O Feudo não tem um campo para o nome da outra parte, mas a descrição enviada pelo banco pode trazê-lo.",
            "Anotações: categorizações, regras, marcações de transferência interna, ajustes da reserva e pesos da comparação de bancos, com quem fez e quando.",
            "Leituras do analista: os números enviados ao modelo, o texto da resposta, a versão das instruções, o modelo usado e quem pediu.",
            "Registro de acesso: quem abriu Visão geral, Transações, Categorias ou Reserva, ou baixou seus dados, em qual casa e quando, sem nenhum valor. Você vê os seus em Casa, em Seus acessos recentes.",
            "Controles de uso: tentativas de autenticação no Meu Pluggy e sincronizações manuais, para aplicar os limites.",
            "Registros técnicos da hospedagem, sem credenciais, documentos, valores ou descrições.",
          ],
          "O Feudo não pede seu CPF, não guarda a senha do seu banco e não vende seus dados nem os usa para publicidade.",
        ],
      },
      {
        title: "Bases legais",
        blocks: [
          [
            "Execução do contrato (art. 7º, V): cadastro, casas, preferências e e-mails do serviço.",
            "Consentimento (art. 7º, I): a leitura dos seus bancos e tudo o que vem dela: credenciais, contas, transações, anotações, cálculos e a leitura do analista. Você pode revogá-lo quando quiser, como explica Seus direitos.",
            "Legítimo interesse (art. 7º, IX): registro de acesso, controles de uso e registros técnicos, para proteger seus dados, evitar abuso e investigar incidentes.",
          ],
        ],
      },
      {
        title: "Com quem compartilhamos",
        blocks: [
          "Seus dados não são vendidos. Os serviços abaixo recebem dados pessoais para que o Feudo funcione:",
          [
            "Pluggy (Brasil): recebe as credenciais da sua aplicação a cada sincronização e devolve os dados dos bancos que você conectou no Meu Pluggy. Sua conta no Meu Pluggy segue os termos da Pluggy.",
            "Anthropic (Estados Unidos): para escrever a leitura do analista, recebe só os números que o Feudo calculou para a casa (totais, taxas, meta e posições da reserva, comparação de bancos) e os nomes das instituições; nunca transações, descrições, nomes de contas, documentos ou credenciais.",
            "Vercel (Estados Unidos): hospeda o aplicativo e guarda os registros técnicos.",
            "Neon (Estados Unidos): hospeda o banco de dados onde tudo isso fica guardado.",
            "Resend (Estados Unidos): envia os e-mails do Feudo (confirmação, link de entrada, redefinição de senha, convites e avisos de exclusão) e recebe o endereço e o conteúdo de cada mensagem.",
            "Membros da casa: veem seu nome e e-mail, as contas que estão na casa, com saldos e transações, e o que é calculado a partir delas. Ninguém além de você vê suas credenciais ou administra suas conexões.",
          ],
          "Os índices CDI, Selic e IPCA vêm do Banco Central (SGS); nessa consulta, nenhum dado seu é enviado.",
          "Também podemos compartilhar dados quando a lei ou uma ordem judicial exigir.",
        ],
      },
      {
        title: "Transferência internacional",
        blocks: [
          "Anthropic, Vercel, Neon e Resend ficam nos Estados Unidos, então seus dados são transferidos para fora do Brasil (art. 33 da LGPD). Essas empresas tratam os dados em nome do Feudo, conforme os contratos e as garantias de proteção de dados que oferecem a seus clientes.",
        ],
      },
      {
        title: "Por quanto tempo guardamos",
        blocks: [
          [
            "Cadastro, preferências e aceite: até a exclusão do seu cadastro.",
            "Credenciais do Meu Pluggy: até você removê-las ou pedir a exclusão do cadastro; nos dois casos, são destruídas na hora.",
            "Conexões, contas e transações: até você excluir a conexão ou o cadastro. Se a casa for excluída, ou se você sair dela, as contas ficam sem casa, visíveis só para você, até você movê-las.",
            "Consentimento: enquanto existir a conexão que ele autorizou. Um consentimento aceito sem que a conexão seja criada é apagado depois de 24 horas.",
            "Dados da casa (configurações, anotações, metas e leituras do analista): até a exclusão da casa. Categorizações e marcações acompanham a transação e são apagadas com ela.",
            "Registro de acesso: 12 meses. Se você excluir seu cadastro, os registros continuam até completar os 12 meses, sem identificar você; se a casa for excluída, os registros dela são apagados.",
            "Convites: valem 24 horas; os vencidos ou cancelados são apagados todo dia.",
            "Links de entrada, de confirmação e de redefinição de senha: até vencerem; os vencidos são apagados todo dia.",
            "Controles de uso: tentativas de autenticação no Meu Pluggy, 15 minutos; sincronizações manuais, 48 horas.",
            "Registros técnicos: o prazo padrão da Vercel.",
          ],
          "Excluir o cadastro ou uma casa dá 7 dias para você desistir; passado esse prazo, os dados são apagados de vez.",
        ],
      },
      {
        title: "Seus direitos",
        blocks: [
          [
            "Confirmação e acesso: em Preferências, Baixar meus dados gera um arquivo com os seus dados: cadastro (com suas sessões de acesso e o aceite destes documentos), preferências e tutoriais, as casas de que você participa e seu papel em cada uma, suas credenciais do Meu Pluggy (só as datas, nunca o segredo), consentimentos, conexões, contas, investimentos, transações, as anotações que você fez e seu registro de acesso. Não entram os dados que são da casa toda (configurações, convites, leituras do analista) nem os controles de uso de curta duração; se quiser, escreva para {contact}. São até 3 downloads a cada 24 horas, e cada um aparece no registro de acesso. Para baixar, você precisa estar numa casa; se não estiver em nenhuma, escreva para {contact} e enviamos o arquivo.",
            "Portabilidade: o mesmo arquivo, num formato aberto (JSON) que outro serviço consegue ler.",
            "Correção: o que vem do banco é corrigido no banco e chega na próxima sincronização; para corrigir seu nome ou e-mail, escreva para {contact}.",
            "Revogação do consentimento: em Suas conexões, remover suas credenciais interrompe a sincronização e as destrói na hora, e excluir uma conexão apaga as contas dela, com as transações. Revogar o acesso do Feudo no Meu Pluggy só interrompe as próximas sincronizações: o que já foi lido continua aqui até você excluir suas conexões.",
            "Eliminação: Excluir meu cadastro, em Preferências, como descrito em Por quanto tempo guardamos.",
            "Informação sobre compartilhamento: Com quem compartilhamos lista todos que recebem seus dados.",
            "Reclamação: você pode reclamar à Autoridade Nacional de Proteção de Dados (ANPD).",
          ],
          "Pedidos por e-mail são respondidos em até 15 dias.",
        ],
      },
      {
        title: "Segurança",
        blocks: [
          "Senhas guardadas só como hash; credenciais do Meu Pluggy criptografadas com AES-256-GCM, com uma chave guardada fora do banco de dados; CPF e CNPJ guardados como código feito com outra chave secreta; conexões sempre por HTTPS; limites de tentativas na entrada, na conexão com o banco, na sincronização e nas leituras do analista; e testes automáticos que verificam, a cada mudança, que uma casa não lê dados de outra.",
          "Se acontecer um incidente de segurança que possa trazer risco ou dano relevante para você, avisaremos você e a ANPD, como a lei manda.",
        ],
      },
      {
        title: "Cookies e dados no seu aparelho",
        blocks: [
          "O Feudo usa só cookies necessários: os de sessão, que mantêm você conectado, e um que lembra se a barra lateral está recolhida. Não há cookies de publicidade nem de análise de uso.",
          "Como o Feudo pode ser instalado como aplicativo, o navegador guarda no aparelho uma cópia das telas que você abriu nas últimas 24 horas, para mostrá-las sem internet. Essa cópia fica só no aparelho e é apagada quando você sai, troca de casa ou pede a exclusão do cadastro; para apagá-la antes, limpe os dados do site nas configurações do navegador.",
        ],
      },
      {
        title: "Crianças e adolescentes",
        blocks: ["O Feudo não é destinado a menores de 18 anos e não deve ser usado por eles."],
      },
      {
        title: "Mudanças nesta política",
        blocks: [
          "Quando esta política mudar, publicamos a versão nova nesta página, com a data, e pedimos seu aceite no próximo acesso.",
        ],
      },
    ],
  },
} satisfies typeof en;

const legalStrings = { en, ptBR };

export const legal = legalStrings.ptBR;
