import type { Kind, ProductCategoryId, ProductSubcategoryId } from "@feudo/core";

type TaxonomyLabels = {
  kinds: Record<Kind, string>;
  categories: Record<ProductCategoryId, string>;
  subcategories: Record<ProductSubcategoryId, string>;
};

const enTaxonomy = {
  kinds: {
    income: "Income",
    fixed: "Fixed",
    variable: "Variable",
    transfer: "Transfer",
  },
  categories: {
    income: "Income",
    housing: "Housing",
    food: "Food",
    transport: "Transport",
    health: "Health",
    education: "Education",
    bills: "Bills and subscriptions",
    shopping: "Shopping",
    leisure: "Leisure",
    financial: "Financial",
    other: "Other spending",
    investments: "Investments",
    transfers: "Transfers",
  },
  subcategories: {
    "income.salary": "Salary",
    "income.self-employed": "Self-employed and owner's draw",
    "income.benefits": "Pension and benefits",
    "income.yields": "Yields",
    "income.rent-received": "Rent received",
    "income.other": "Other income",
    "housing.rent": "Rent",
    "housing.condo": "Condominium fee",
    "housing.mortgage": "Mortgage",
    "housing.utilities": "Power, water and gas",
    "housing.property-tax": "Property tax (IPTU)",
    "housing.repairs": "Maintenance and repairs",
    "food.groceries": "Groceries",
    "food.restaurants": "Restaurants",
    "food.delivery": "Delivery",
    "transport.fuel": "Fuel",
    "transport.public": "Public transport",
    "transport.ride-hailing": "Taxis and ride-hailing",
    "transport.parking-tolls": "Parking and tolls",
    "transport.vehicle-maintenance": "Vehicle maintenance",
    "transport.vehicle-taxes": "Vehicle tax and licensing",
    "transport.vehicle-financing": "Vehicle financing",
    "health.insurance": "Health plan",
    "health.pharmacy": "Pharmacy",
    "health.doctors": "Doctors and tests",
    "health.dentist": "Dentist",
    "health.fitness": "Gym and sports",
    "health.personal-care": "Beauty and personal care",
    "education.tuition": "School and university",
    "education.courses": "Courses",
    "education.books": "Books and supplies",
    "bills.telecom": "Internet, TV and phone",
    "bills.subscriptions": "Streaming and apps",
    "bills.insurance": "Insurance",
    "shopping.clothing": "Clothing",
    "shopping.electronics": "Electronics",
    "shopping.home": "Home and decor",
    "shopping.pets": "Pets",
    "shopping.online": "Online shopping",
    "shopping.other": "Other shopping",
    "leisure.travel": "Travel",
    "leisure.outings": "Outings and events",
    "leisure.gaming": "Games and betting",
    "financial.bank-fees": "Bank fees",
    "financial.interest": "Interest and fines",
    "financial.taxes": "Taxes",
    "financial.loans": "Loans",
    "other.donations": "Donations",
    "other.gifts": "Gifts",
    "other.alimony": "Alimony",
    "investments.movements": "Contributions and withdrawals",
    "transfers.own-accounts": "Between household accounts",
    "transfers.card-bill": "Card bill payment",
  },
} satisfies TaxonomyLabels;

const ptBRTaxonomy = {
  kinds: {
    income: "Renda",
    fixed: "Fixo",
    variable: "Variável",
    transfer: "Transferência",
  },
  categories: {
    income: "Renda",
    housing: "Moradia",
    food: "Alimentação",
    transport: "Transporte",
    health: "Saúde",
    education: "Educação",
    bills: "Contas e assinaturas",
    shopping: "Compras",
    leisure: "Lazer",
    financial: "Financeiro",
    other: "Outros gastos",
    investments: "Investimentos",
    transfers: "Transferências",
  },
  subcategories: {
    "income.salary": "Salário",
    "income.self-employed": "Autônomo e pró-labore",
    "income.benefits": "Aposentadoria e benefícios",
    "income.yields": "Rendimentos",
    "income.rent-received": "Aluguel recebido",
    "income.other": "Outras rendas",
    "housing.rent": "Aluguel",
    "housing.condo": "Condomínio",
    "housing.mortgage": "Financiamento imobiliário",
    "housing.utilities": "Luz, água e gás",
    "housing.property-tax": "IPTU",
    "housing.repairs": "Manutenção e reparos",
    "food.groceries": "Mercado",
    "food.restaurants": "Restaurantes",
    "food.delivery": "Delivery",
    "transport.fuel": "Combustível",
    "transport.public": "Transporte público",
    "transport.ride-hailing": "Táxi e aplicativos",
    "transport.parking-tolls": "Estacionamento e pedágio",
    "transport.vehicle-maintenance": "Manutenção do veículo",
    "transport.vehicle-taxes": "IPVA e licenciamento",
    "transport.vehicle-financing": "Financiamento do veículo",
    "health.insurance": "Plano de saúde",
    "health.pharmacy": "Farmácia",
    "health.doctors": "Consultas e exames",
    "health.dentist": "Dentista",
    "health.fitness": "Academia e esportes",
    "health.personal-care": "Beleza e cuidados pessoais",
    "education.tuition": "Escola e faculdade",
    "education.courses": "Cursos",
    "education.books": "Livros e material",
    "bills.telecom": "Internet, TV e celular",
    "bills.subscriptions": "Streaming e apps",
    "bills.insurance": "Seguros",
    "shopping.clothing": "Roupas",
    "shopping.electronics": "Eletrônicos",
    "shopping.home": "Casa e decoração",
    "shopping.pets": "Pets",
    "shopping.online": "Compras online",
    "shopping.other": "Outras compras",
    "leisure.travel": "Viagens",
    "leisure.outings": "Passeios e eventos",
    "leisure.gaming": "Jogos e apostas",
    "financial.bank-fees": "Tarifas bancárias",
    "financial.interest": "Juros e multas",
    "financial.taxes": "Impostos",
    "financial.loans": "Empréstimos",
    "other.donations": "Doações",
    "other.gifts": "Presentes",
    "other.alimony": "Pensão alimentícia",
    "investments.movements": "Aplicações e resgates",
    "transfers.own-accounts": "Entre contas da casa",
    "transfers.card-bill": "Pagamento de fatura",
  },
} satisfies TaxonomyLabels;

const en = {
  ...enTaxonomy,
  overline: "Transactions",
  headline: {
    none: "No transactions in {month}",
    one: "1 transaction in {month}",
    many: "{count} transactions in {month}",
  },
  monthSwitcher: {
    previous: "Previous month",
    next: "Next month",
  },
  accountFilter: {
    label: "Account",
    all: "All accounts",
  },
  table: {
    date: "Date",
    description: "Description",
    account: "Account",
    amount: "Amount",
    category: "Category",
  },
  empty: {
    noAccounts: "Connect a bank to see the household's transactions here.",
    connectAction: "Connect bank",
    noTransactions: "Nothing recorded in {month}.",
  },
  pagination: {
    label: "Pages",
    page: "Page {page}",
    newer: "Newer",
    older: "Older",
  },
  uncategorizedHeadline: {
    none: "Everything in {month} has a category",
    one: "1 transaction without a category in {month}",
    many: "{count} transactions without a category in {month}",
  },
  uncategorized: {
    one: "1 transaction in {month} has no category yet ({amount}). It counts in no total until it gets one.",
    many: "{count} transactions in {month} have no category yet ({amount}). They count in no total until they get one.",
    show: "Categorize them",
    showAll: "Show all transactions",
  },
  categoriesLink: "Categories and rules",
  category: {
    uncategorized: "No category",
    sources: {
      manual: "Chosen by hand",
      rule: "From a household rule",
      default: "Recognized by Feudo",
      provider: "Category from the bank",
    },
  },
  categorize: {
    action: "Categorize",
    actionFor: "Categorize {description}",
    title: "Categorize transaction",
    label: "Subcategory",
    placeholder: "Choose a subcategory",
    createRule: "Do the same for every transaction whose description contains:",
    patternLabel: "Text to look for",
    patternHint: "Whole words, ignoring accents and capital letters.",
    direction: {
      credit: "Incoming transactions only.",
      debit: "Outgoing transactions only.",
    },
    submit: "Save",
    cancel: "Cancel",
    resetAction: "Back to automatic",
    saved: "Category saved.",
    resetDone: "The transaction follows the rules again.",
  },
  categoriesPage: {
    overline: "Categories",
    title: "Categories and rules",
    rulesTitle: "Household rules",
    rulesEmpty: "No rules yet. Create one when you categorize a transaction.",
    ruleTable: {
      pattern: "When the description contains",
      direction: "Applies to",
      target: "Goes to",
      any: "Incoming and outgoing",
      credit: "Incoming",
      debit: "Outgoing",
    },
    removeRule: "Remove",
    removeRuleFor: "Remove the rule for {pattern}",
    subcategoriesTitle: "Subcategories",
    kindLabelFor: "Kind of {subcategory}",
    householdBadge: "Household",
    kindChanged: "Kind updated.",
    addAction: "New subcategory",
    addDialog: {
      title: "New subcategory",
      description: "It shows up only for this household, under the category you pick.",
      category: "Category",
      name: "Name",
      kind: "Kind",
      submit: "Create",
      cancel: "Cancel",
      added: "Subcategory created.",
    },
    suggestions: {
      title: "Looks like a fixed cost",
      description:
        "Spending that repeated with a similar amount in each of the last three months. Marking it fixed changes the subcategory's kind for every month.",
      item: "{subcategory}: “{description}”",
      action: "Mark as fixed",
      actionFor: "Mark {subcategory} as fixed",
    },
  },
  rules: {
    removed: "Rule removed.",
  },
  errors: {
    invalidInput: "Check the fields and try again.",
    invalidPattern: "Use at least 3 letters or numbers in the rule's text.",
    notFound: "That transaction or subcategory is no longer available in this household.",
    failed: "Couldn't save right now. Try again.",
    duplicateSubcategory: "This category already has a subcategory with that name.",
  },
};

const ptBR = {
  ...ptBRTaxonomy,
  overline: "Transações",
  headline: {
    none: "Nenhuma transação em {month}",
    one: "1 transação em {month}",
    many: "{count} transações em {month}",
  },
  monthSwitcher: {
    previous: "Mês anterior",
    next: "Próximo mês",
  },
  accountFilter: {
    label: "Conta",
    all: "Todas as contas",
  },
  table: {
    date: "Data",
    description: "Descrição",
    account: "Conta",
    amount: "Valor",
    category: "Categoria",
  },
  empty: {
    noAccounts: "Conecte um banco para ver as transações da casa aqui.",
    connectAction: "Conectar banco",
    noTransactions: "Nada registrado em {month}.",
  },
  pagination: {
    label: "Páginas",
    page: "Página {page}",
    newer: "Mais recentes",
    older: "Mais antigas",
  },
  uncategorizedHeadline: {
    none: "Tudo categorizado em {month}",
    one: "1 transação sem categoria em {month}",
    many: "{count} transações sem categoria em {month}",
  },
  uncategorized: {
    one: "1 transação de {month} ainda está sem categoria ({amount}). Ela fica fora de todos os totais até ganhar uma.",
    many: "{count} transações de {month} ainda estão sem categoria ({amount}). Elas ficam fora de todos os totais até ganharem uma.",
    show: "Categorizar agora",
    showAll: "Ver todas as transações",
  },
  categoriesLink: "Categorias e regras",
  category: {
    uncategorized: "Sem categoria",
    sources: {
      manual: "Escolhida à mão",
      rule: "Por uma regra da casa",
      default: "Reconhecida pelo Feudo",
      provider: "Categoria do banco",
    },
  },
  categorize: {
    action: "Categorizar",
    actionFor: "Categorizar {description}",
    title: "Categorizar transação",
    label: "Subcategoria",
    placeholder: "Escolha uma subcategoria",
    createRule: "Fazer o mesmo com toda transação cuja descrição contenha:",
    patternLabel: "Texto a procurar",
    patternHint: "Palavras inteiras, sem diferenciar acentos nem maiúsculas.",
    direction: {
      credit: "Só nas entradas.",
      debit: "Só nas saídas.",
    },
    submit: "Salvar",
    cancel: "Cancelar",
    resetAction: "Voltar ao automático",
    saved: "Categoria salva.",
    resetDone: "A transação voltou a seguir as regras.",
  },
  categoriesPage: {
    overline: "Categorias",
    title: "Categorias e regras",
    rulesTitle: "Regras da casa",
    rulesEmpty: "Nenhuma regra ainda. Crie uma ao categorizar uma transação.",
    ruleTable: {
      pattern: "Quando a descrição contém",
      direction: "Vale para",
      target: "Vai para",
      any: "Entradas e saídas",
      credit: "Entradas",
      debit: "Saídas",
    },
    removeRule: "Remover",
    removeRuleFor: "Remover a regra de {pattern}",
    subcategoriesTitle: "Subcategorias",
    kindLabelFor: "Tipo de {subcategory}",
    householdBadge: "Da casa",
    kindChanged: "Tipo atualizado.",
    addAction: "Nova subcategoria",
    addDialog: {
      title: "Nova subcategoria",
      description: "Ela aparece só para esta casa, dentro da categoria que você escolher.",
      category: "Categoria",
      name: "Nome",
      kind: "Tipo",
      submit: "Criar",
      cancel: "Cancelar",
      added: "Subcategoria criada.",
    },
    suggestions: {
      title: "Parece custo fixo",
      description:
        "Gastos que se repetiram com valor parecido em cada um dos últimos três meses. Marcar como fixo muda o tipo da subcategoria em todos os meses.",
      item: "{subcategory}: “{description}”",
      action: "Marcar como fixo",
      actionFor: "Marcar {subcategory} como fixo",
    },
  },
  rules: {
    removed: "Regra removida.",
  },
  errors: {
    invalidInput: "Confira os campos e tente de novo.",
    invalidPattern: "Use pelo menos 3 letras ou números no texto da regra.",
    notFound: "Essa transação ou subcategoria não está mais disponível nesta casa.",
    failed: "Não deu para salvar agora. Tente de novo.",
    duplicateSubcategory: "Essa categoria já tem uma subcategoria com esse nome.",
  },
} satisfies typeof en;

const ledgerStrings = { en, ptBR };

export const t = ledgerStrings.ptBR;
