import type { Kind, ProductCategoryId, ProductSubcategoryId } from "@feudo/core";

type TaxonomyLabels = {
  kinds: Record<Kind, string>;
  categories: Record<ProductCategoryId, string>;
  subcategories: Record<ProductSubcategoryId, string>;
};

const enTaxonomy = {
  kinds: {
    income: "Income",
    fixed: "Fixed",
    variable: "Variable",
    transfer: "Transfer",
  },
  categories: {
    income: "Income",
    housing: "Housing",
    food: "Food",
    transport: "Transport",
    health: "Health",
    education: "Education",
    bills: "Bills and subscriptions",
    shopping: "Shopping",
    leisure: "Leisure",
    financial: "Financial",
    other: "Other spending",
    investments: "Investments",
    transfers: "Transfers",
  },
  subcategories: {
    "income.salary": "Salary",
    "income.self-employed": "Self-employed and owner's draw",
    "income.benefits": "Pension and benefits",
    "income.yields": "Yields",
    "income.rent-received": "Rent received",
    "income.other": "Other income",
    "housing.rent": "Rent",
    "housing.condo": "Condominium fee",
    "housing.mortgage": "Mortgage",
    "housing.utilities": "Power, water and gas",
    "housing.property-tax": "Property tax (IPTU)",
    "housing.repairs": "Maintenance and repairs",
    "food.groceries": "Groceries",
    "food.restaurants": "Restaurants",
    "food.delivery": "Delivery",
    "transport.fuel": "Fuel",
    "transport.public": "Public transport",
    "transport.ride-hailing": "Taxis and ride-hailing",
    "transport.parking-tolls": "Parking and tolls",
    "transport.vehicle-maintenance": "Vehicle maintenance",
    "transport.vehicle-taxes": "Vehicle tax and licensing",
    "transport.vehicle-financing": "Vehicle financing",
    "health.insurance": "Health plan",
    "health.pharmacy": "Pharmacy",
    "health.doctors": "Doctors and tests",
    "health.dentist": "Dentist",
    "health.fitness": "Gym and sports",
    "health.personal-care": "Beauty and personal care",
    "education.tuition": "School and university",
    "education.courses": "Courses",
    "education.books": "Books and supplies",
    "bills.telecom": "Internet, TV and phone",
    "bills.subscriptions": "Streaming and apps",
    "bills.insurance": "Insurance",
    "shopping.clothing": "Clothing",
    "shopping.electronics": "Electronics",
    "shopping.home": "Home and decor",
    "shopping.pets": "Pets",
    "shopping.online": "Online shopping",
    "shopping.other": "Other shopping",
    "leisure.travel": "Travel",
    "leisure.outings": "Outings and events",
    "leisure.gaming": "Games and betting",
    "financial.bank-fees": "Bank fees",
    "financial.interest": "Interest and fines",
    "financial.taxes": "Taxes",
    "financial.loans": "Loans",
    "other.donations": "Donations",
    "other.gifts": "Gifts",
    "other.alimony": "Alimony",
    "investments.movements": "Contributions and withdrawals",
    "transfers.own-accounts": "Between household accounts",
    "transfers.card-bill": "Card bill payment",
  },
} satisfies TaxonomyLabels;

const ptBRTaxonomy = {
  kinds: {
    income: "Renda",
    fixed: "Fixo",
    variable: "Variável",
    transfer: "Transferência",
  },
  categories: {
    income: "Renda",
    housing: "Moradia",
    food: "Alimentação",
    transport: "Transporte",
    health: "Saúde",
    education: "Educação",
    bills: "Contas e assinaturas",
    shopping: "Compras",
    leisure: "Lazer",
    financial: "Financeiro",
    other: "Outros gastos",
    investments: "Investimentos",
    transfers: "Transferências",
  },
  subcategories: {
    "income.salary": "Salário",
    "income.self-employed": "Autônomo e pró-labore",
    "income.benefits": "Aposentadoria e benefícios",
    "income.yields": "Rendimentos",
    "income.rent-received": "Aluguel recebido",
    "income.other": "Outras rendas",
    "housing.rent": "Aluguel",
    "housing.condo": "Condomínio",
    "housing.mortgage": "Financiamento imobiliário",
    "housing.utilities": "Luz, água e gás",
    "housing.property-tax": "IPTU",
    "housing.repairs": "Manutenção e reparos",
    "food.groceries": "Mercado",
    "food.restaurants": "Restaurantes",
    "food.delivery": "Delivery",
    "transport.fuel": "Combustível",
    "transport.public": "Transporte público",
    "transport.ride-hailing": "Táxi e aplicativos",
    "transport.parking-tolls": "Estacionamento e pedágio",
    "transport.vehicle-maintenance": "Manutenção do veículo",
    "transport.vehicle-taxes": "IPVA e licenciamento",
    "transport.vehicle-financing": "Financiamento do veículo",
    "health.insurance": "Plano de saúde",
    "health.pharmacy": "Farmácia",
    "health.doctors": "Consultas e exames",
    "health.dentist": "Dentista",
    "health.fitness": "Academia e esportes",
    "health.personal-care": "Beleza e cuidados pessoais",
    "education.tuition": "Escola e faculdade",
    "education.courses": "Cursos",
    "education.books": "Livros e material",
    "bills.telecom": "Internet, TV e celular",
    "bills.subscriptions": "Streaming e apps",
    "bills.insurance": "Seguros",
    "shopping.clothing": "Roupas",
    "shopping.electronics": "Eletrônicos",
    "shopping.home": "Casa e decoração",
    "shopping.pets": "Pets",
    "shopping.online": "Compras online",
    "shopping.other": "Outras compras",
    "leisure.travel": "Viagens",
    "leisure.outings": "Passeios e eventos",
    "leisure.gaming": "Jogos e apostas",
    "financial.bank-fees": "Tarifas bancárias",
    "financial.interest": "Juros e multas",
    "financial.taxes": "Impostos",
    "financial.loans": "Empréstimos",
    "other.donations": "Doações",
    "other.gifts": "Presentes",
    "other.alimony": "Pensão alimentícia",
    "investments.movements": "Aplicações e resgates",
    "transfers.own-accounts": "Entre contas da casa",
    "transfers.card-bill": "Pagamento de fatura",
  },
} satisfies TaxonomyLabels;

const en = {
  ...enTaxonomy,
  overline: "Transactions",
  headline: {
    none: "No transactions in {month}",
    one: "1 transaction in {month}",
    many: "{count} transactions in {month}",
    found: {
      none: "No transactions found in {month}",
      one: "1 transaction found in {month}",
      many: "{count} transactions found in {month}",
    },
  },
  monthSwitcher: {
    previous: "Previous month",
    next: "Next month",
  },
  accountFilter: {
    label: "Account",
    all: "All accounts",
  },
  categoryFilter: {
    label: "Category",
    all: "All categories",
    uncategorized: "No category",
  },
  kindFilter: {
    label: "Kind",
    all: "All kinds",
  },
  search: {
    label: "Search transactions",
    placeholder: "Search by description",
  },
  filters: {
    clear: "Clear filters",
  },
  table: {
    date: "Date",
    description: "Description",
    account: "Account",
    amount: "Amount",
    category: "Category",
  },
  empty: {
    noAccounts: "Connect a bank to see the household's transactions here.",
    connectAction: "Connect bank",
    noTransactions: "Nothing recorded in {month}.",
    noMatches: "No transactions in {month} match these filters.",
  },
  pagination: {
    label: "Pages",
    page: "Page {page}",
    newer: "Newer",
    older: "Older",
  },
  uncategorizedHeadline: {
    none: "Everything in {month} has a category",
    one: "1 transaction without a category in {month}",
    many: "{count} transactions without a category in {month}",
  },
  uncategorized: {
    one: "1 transaction in {month} has no category yet ({amount}). It counts in no total until it gets one.",
    many: "{count} transactions in {month} have no category yet ({amount}). They count in no total until they get one.",
    show: "Categorize them",
  },
  totals: {
    income: "Income {amount}",
    spending: "Spending {amount}",
    transfersOne: "1 transfer transaction left out of the totals",
    transfersMany: "{count} transfer transactions left out of the totals",
  },
  categoriesLink: "Categories and rules",
  error: {
    message: "Couldn't load the transactions right now. Check your connection and try again.",
    retry: "Try again",
  },
  category: {
    uncategorized: "No category",
    sources: {
      manual: "Chosen by hand",
      rule: "From a household rule",
      default: "Recognized by Feudo",
      provider: "Category from the bank",
      internal_transfer: "Internal transfer",
    },
    transferTooltip: {
      pair: "Paired with {institution} · {account}, {date}",
      mark: "Marked by hand as an internal transfer",
    },
  },
  categorize: {
    action: "Categorize",
    actionFor: "Categorize {description}",
    title: "Categorize transaction",
    label: "Subcategory",
    placeholder: "Choose a subcategory",
    createRule: "Do the same for every transaction whose description contains:",
    patternLabel: "Text to look for",
    patternHint: "Whole words, ignoring accents and capital letters.",
    direction: {
      credit: "Incoming transactions only.",
      debit: "Outgoing transactions only.",
    },
    submit: "Save",
    cancel: "Cancel",
    resetAction: "Back to automatic",
    saved: "Category saved.",
    resetDone: "The transaction follows the rules again.",
    transfer: {
      sectionLabel: "Internal transfer",
      mark: "Internal transfer",
      unmark: "Not an internal transfer",
      backToAutomatic: "Let Feudo detect it",
      marked: "Marked as an internal transfer.",
      unmarked: "Marked as not an internal transfer.",
      cleared: "Back to automatic detection.",
    },
  },
  categoriesPage: {
    overline: "Categories",
    error: {
      message:
        "Couldn't load the categories and rules right now. Check your connection and try again.",
      retry: "Try again",
    },
    title: "Categories and rules",
    rulesTitle: "Household rules",
    rulesEmpty: "No rules yet. Create one when you categorize a transaction.",
    ruleTable: {
      pattern: "When the description contains",
      direction: "Applies to",
      target: "Goes to",
      any: "Incoming and outgoing",
      credit: "Incoming",
      debit: "Outgoing",
    },
    removeRule: "Remove",
    removeRuleFor: "Remove the rule for {pattern}",
    subcategoriesTitle: "Subcategories",
    kindLabelFor: "Kind of {subcategory}",
    householdBadge: "Household",
    kindChanged: "Kind updated.",
    addAction: "New subcategory",
    addDialog: {
      title: "New subcategory",
      description: "It shows up only for this household, under the category you pick.",
      category: "Category",
      name: "Name",
      kind: "Kind",
      submit: "Create",
      cancel: "Cancel",
      added: "Subcategory created.",
    },
    suggestions: {
      title: "Looks like a fixed cost",
      description:
        "Spending that repeated with a similar amount in each of the last three months. Marking it fixed changes the subcategory's kind for every month.",
      item: "{subcategory}: “{description}”",
      action: "Mark as fixed",
      actionFor: "Mark {subcategory} as fixed",
    },
  },
  rules: {
    removed: "Rule removed.",
  },
  overview: {
    overline: "Overview",
    headline: {
      kept: "The household kept {percent} of its income in {month}.",
      overspent: "The household spent more than it received in {month}.",
      noIncome: "The household spent {amount} in {month} with no income registered.",
      negativeIncome:
        "The household's income was negative in {month} ({amount}), with no spending registered.",
      noActivity: "Nothing was registered in {month}.",
    },
    inProgressSuffix: "so far",
    uncategorized: {
      one: "1 transaction in {month} has no category yet ({amount}). It stays out of every number here until it gets one.",
      many: "{count} transactions in {month} have no category yet ({amount}). They stay out of every number here until they get one.",
      action: "Categorize them",
    },
    otherCurrencyNotice:
      "Accounts in another currency stay out of these numbers; see them in Transactions.",
    tiles: {
      income: "Income",
      spending: "Spending",
      spendingMeta: "Fixed {fixed} · Variable {variable}",
      savingsRate: "Savings rate",
      savingsRateNoIncome: "No income registered this month.",
      averageFixedCost: "Average fixed cost",
      averageFixedCostAverage: "average of {count} months",
      averageFixedCostEstimate: "estimate based on: {months}",
      averageFixedCostNoHistory: "No fixed-cost history yet.",
    },
    categorySpending: {
      title: "Spending by category",
      empty: "No categorized spending this month.",
    },
    chart: {
      title: "Last six months",
      income: "Income",
      spending: "Spending",
      month: "Month",
      accessibleName: "Income and spending from {from} to {to}",
    },
    empty: {
      noAccounts: "Connect a bank to see the household's spending here.",
    },
    error: {
      message: "Couldn't load the overview right now. Check your connection and try again.",
      retry: "Try again",
    },
  },
  analysisFacts: {
    month: "Month analysed",
    inProgress: "{month} (in progress)",
    income: "Income in {month}",
    spending: "Spending in {month}",
    spendingSplit: "Fixed and variable spending in {month}",
    savingsRate: "Savings rate in {month}",
    averageFixedCost: "Average fixed cost",
    averageFixedCostValue: "{value} ({meta})",
    uncategorized: "Uncategorized transactions in {month}",
    uncategorizedValue: "{count} transactions, {amount}, left out of the numbers",
    uncategorizedNone: "none",
    category: "Spending on {category} in {month}",
    seriesIncome: "Income in {month}",
    seriesSpending: "Spending in {month}",
    otherCurrency: "Accounts in a foreign currency",
    otherCurrencyValue: "left out of these numbers",
  },
  errors: {
    invalidInput: "Check the fields and try again.",
    invalidPattern: "Use at least 3 letters or numbers in the rule's text.",
    notFound: "That transaction or subcategory is no longer available in this household.",
    failed: "Couldn't save right now. Try again.",
    duplicateSubcategory: "This category already has a subcategory with that name.",
  },
};

const ptBR = {
  ...ptBRTaxonomy,
  overline: "Transações",
  headline: {
    none: "Nenhuma transação em {month}",
    one: "1 transação em {month}",
    many: "{count} transações em {month}",
    found: {
      none: "Nenhuma transação encontrada em {month}",
      one: "1 transação encontrada em {month}",
      many: "{count} transações encontradas em {month}",
    },
  },
  monthSwitcher: {
    previous: "Mês anterior",
    next: "Próximo mês",
  },
  accountFilter: {
    label: "Conta",
    all: "Todas as contas",
  },
  categoryFilter: {
    label: "Categoria",
    all: "Todas as categorias",
    uncategorized: "Sem categoria",
  },
  kindFilter: {
    label: "Tipo",
    all: "Todos os tipos",
  },
  search: {
    label: "Buscar transações",
    placeholder: "Buscar pela descrição",
  },
  filters: {
    clear: "Limpar filtros",
  },
  table: {
    date: "Data",
    description: "Descrição",
    account: "Conta",
    amount: "Valor",
    category: "Categoria",
  },
  empty: {
    noAccounts: "Conecte um banco para ver as transações da casa aqui.",
    connectAction: "Conectar banco",
    noTransactions: "Nada registrado em {month}.",
    noMatches: "Nenhuma transação de {month} com esses filtros.",
  },
  pagination: {
    label: "Páginas",
    page: "Página {page}",
    newer: "Mais recentes",
    older: "Mais antigas",
  },
  uncategorizedHeadline: {
    none: "Tudo categorizado em {month}",
    one: "1 transação sem categoria em {month}",
    many: "{count} transações sem categoria em {month}",
  },
  uncategorized: {
    one: "1 transação de {month} ainda está sem categoria ({amount}). Ela fica fora de todos os totais até ganhar uma.",
    many: "{count} transações de {month} ainda estão sem categoria ({amount}). Elas ficam fora de todos os totais até ganharem uma.",
    show: "Categorizar agora",
  },
  totals: {
    income: "Renda {amount}",
    spending: "Gastos {amount}",
    transfersOne: "1 transação de transferência ficou fora dos totais",
    transfersMany: "{count} transações de transferência ficaram fora dos totais",
  },
  categoriesLink: "Categorias e regras",
  error: {
    message: "Não deu para carregar as transações agora. Confira sua conexão e tente de novo.",
    retry: "Tentar de novo",
  },
  category: {
    uncategorized: "Sem categoria",
    sources: {
      manual: "Escolhida à mão",
      rule: "Por uma regra da casa",
      default: "Reconhecida pelo Feudo",
      provider: "Categoria do banco",
      internal_transfer: "Transferência interna",
    },
    transferTooltip: {
      pair: "Pareada com {institution} · {account}, {date}",
      mark: "Marcada à mão como transferência interna",
    },
  },
  categorize: {
    action: "Categorizar",
    actionFor: "Categorizar {description}",
    title: "Categorizar transação",
    label: "Subcategoria",
    placeholder: "Escolha uma subcategoria",
    createRule: "Fazer o mesmo com toda transação cuja descrição contenha:",
    patternLabel: "Texto a procurar",
    patternHint: "Palavras inteiras, sem diferenciar acentos nem maiúsculas.",
    direction: {
      credit: "Só nas entradas.",
      debit: "Só nas saídas.",
    },
    submit: "Salvar",
    cancel: "Cancelar",
    resetAction: "Voltar ao automático",
    saved: "Categoria salva.",
    resetDone: "A transação voltou a seguir as regras.",
    transfer: {
      sectionLabel: "Transferência interna",
      mark: "É transferência interna",
      unmark: "Não é transferência interna",
      backToAutomatic: "Deixar o Feudo detectar",
      marked: "Marcada como transferência interna.",
      unmarked: "Marcada como não sendo transferência interna.",
      cleared: "Voltou à detecção automática.",
    },
  },
  categoriesPage: {
    overline: "Categorias",
    error: {
      message:
        "Não deu para carregar as categorias e regras agora. Confira sua conexão e tente de novo.",
      retry: "Tentar de novo",
    },
    title: "Categorias e regras",
    rulesTitle: "Regras da casa",
    rulesEmpty: "Nenhuma regra ainda. Crie uma ao categorizar uma transação.",
    ruleTable: {
      pattern: "Quando a descrição contém",
      direction: "Vale para",
      target: "Vai para",
      any: "Entradas e saídas",
      credit: "Entradas",
      debit: "Saídas",
    },
    removeRule: "Remover",
    removeRuleFor: "Remover a regra de {pattern}",
    subcategoriesTitle: "Subcategorias",
    kindLabelFor: "Tipo de {subcategory}",
    householdBadge: "Da casa",
    kindChanged: "Tipo atualizado.",
    addAction: "Nova subcategoria",
    addDialog: {
      title: "Nova subcategoria",
      description: "Ela aparece só para esta casa, dentro da categoria que você escolher.",
      category: "Categoria",
      name: "Nome",
      kind: "Tipo",
      submit: "Criar",
      cancel: "Cancelar",
      added: "Subcategoria criada.",
    },
    suggestions: {
      title: "Parece custo fixo",
      description:
        "Gastos que se repetiram com valor parecido em cada um dos últimos três meses. Marcar como fixo muda o tipo da subcategoria em todos os meses.",
      item: "{subcategory}: “{description}”",
      action: "Marcar como fixo",
      actionFor: "Marcar {subcategory} como fixo",
    },
  },
  rules: {
    removed: "Regra removida.",
  },
  overview: {
    overline: "Visão geral",
    headline: {
      kept: "A casa guardou {percent} da renda em {month}.",
      overspent: "A casa gastou mais do que recebeu em {month}.",
      noIncome: "A casa gastou {amount} em {month} sem nenhuma renda registrada.",
      negativeIncome:
        "A renda da casa ficou negativa em {month} ({amount}), sem gastos registrados.",
      noActivity: "Nada foi registrado em {month}.",
    },
    inProgressSuffix: "até agora",
    uncategorized: {
      one: "1 transação de {month} está sem categoria ({amount}) e fica fora destes números até ser categorizada.",
      many: "{count} transações de {month} estão sem categoria ({amount}) e ficam fora destes números até serem categorizadas.",
      action: "Categorizar agora",
    },
    otherCurrencyNotice: "Contas em outra moeda ficam fora desses números; veja-as em Transações.",
    tiles: {
      income: "Renda",
      spending: "Gastos",
      spendingMeta: "Fixos {fixed} · Variáveis {variable}",
      savingsRate: "Taxa de poupança",
      savingsRateNoIncome: "Sem renda registrada neste mês.",
      averageFixedCost: "Custo fixo médio",
      averageFixedCostAverage: "média de {count} meses",
      averageFixedCostEstimate: "estimativa com base em: {months}",
      averageFixedCostNoHistory: "Ainda sem histórico de custo fixo.",
    },
    categorySpending: {
      title: "Gastos por categoria",
      empty: "Nenhum gasto categorizado neste mês.",
    },
    chart: {
      title: "Últimos seis meses",
      income: "Renda",
      spending: "Gastos",
      month: "Mês",
      accessibleName: "Renda e gastos de {from} a {to}",
    },
    empty: {
      noAccounts: "Conecte um banco para ver os gastos da casa aqui.",
    },
    error: {
      message: "Não deu para carregar a visão geral agora. Confira sua conexão e tente de novo.",
      retry: "Tentar de novo",
    },
  },
  analysisFacts: {
    month: "Mês analisado",
    inProgress: "{month} (em andamento)",
    income: "Renda em {month}",
    spending: "Gastos em {month}",
    spendingSplit: "Gastos fixos e variáveis em {month}",
    savingsRate: "Taxa de poupança em {month}",
    averageFixedCost: "Custo fixo médio",
    averageFixedCostValue: "{value} ({meta})",
    uncategorized: "Transações sem categoria em {month}",
    uncategorizedValue: "{count} transações, {amount}, fora destes números",
    uncategorizedNone: "nenhuma",
    category: "Gastos com {category} em {month}",
    seriesIncome: "Renda em {month}",
    seriesSpending: "Gastos em {month}",
    otherCurrency: "Contas em moeda estrangeira",
    otherCurrencyValue: "ficam fora destes números",
  },
  errors: {
    invalidInput: "Confira os campos e tente de novo.",
    invalidPattern: "Use pelo menos 3 letras ou números no texto da regra.",
    notFound: "Essa transação ou subcategoria não está mais disponível nesta casa.",
    failed: "Não deu para salvar agora. Tente de novo.",
    duplicateSubcategory: "Essa categoria já tem uma subcategoria com esse nome.",
  },
} satisfies typeof en;

const ledgerStrings = { en, ptBR };

export const t = ledgerStrings.ptBR;
