const en = {
  overline: "Reserve",
  headline: {
    target: "Your target is {amount}.",
    estimate: "Your estimated target is {amount}.",
    noAccounts: "Connect a bank to see the household's reserve target.",
    noHistory: "Categorize at least one month of spending to see the reserve target.",
  },
  multipleSelect: {
    label: "Reserve multiple",
    readOnly: "{multiple} months",
  },
  tiles: {
    target: "Reserve target",
    targetMeta: "{multiple} months of fixed cost",
    averageFixedCost: "Average fixed cost",
    averageFixedCostFull: "average of 6 months",
    averageFixedCostPartial: "average of: {months}",
    averageFixedCostEstimate: "estimate based on: {months}",
    currentReserve: "Current reserve",
    currentReserveMeta: "Shows up once an account is marked part of the reserve.",
    currentReserveCount: "{count} accounts in the reserve",
    currentReserveOne: "1 account in the reserve",
    coverage: "Coverage",
    coverageMeta: "Comes from the reserve's own positions, once there are any.",
    coverageMonths: "{months} months of fixed cost",
  },
  monthlyTable: {
    title: "Fixed cost by month",
    month: "Month",
    amount: "Fixed cost",
    gap: "nothing categorized yet",
  },
  notice: {
    message: "The reserve target moved from {from} to {to} at the {month} close.",
    action: "Got it",
  },
  noticeBanner: {
    action: "See reserve",
  },
  coverage: {
    title: "Coverage",
    summary: "{current} of {target}",
    months: "{months} months of fixed cost",
    progressLabel: "Share of the reserve target covered",
    empty: "Mark the accounts that make up the reserve to see how far it goes.",
  },
  positions: {
    title: "Accounts and investments",
    meta: "mark what makes up the reserve",
    account: "Account",
    balance: "Balance",
    liquidity: "Liquidity",
    tax: "Income tax",
    realYield: "Real yield",
    reserve: "Reserve",
    inReserve: "in the reserve",
    notInReserve: "—",
    adjust: "Adjust",
    adjustFor: "Adjust {account}",
    advice: {
      suggest: "liquid and protected, can be part of the reserve",
      not_liquid: "in the reserve, but not redeemable within 1 business day",
      liquidity_unknown: "in the reserve, liquidity unknown: confirm",
    },
    empty: "No account or investment can hold the reserve yet.",
  },
  liquidity: {
    daily: "up to D+1",
    not_daily: "beyond D+1",
    unknown: "confirm",
  },
  tax: {
    bracket: "{rate}",
    acquisitionDateUnknown: "{rate}, acquisition date unknown",
    exempt: "exempt",
    none: "—",
  },
  yield: {
    perYear: "{rate} a year",
    unknown: "—",
  },
  ranking: {
    title: "Where the next reais should go",
    meta: "liquid in up to 1 business day and protected, by real yield after tax",
    place: "{place}.",
    netYield: "{rate} a year after tax",
    fgc: "FGC: {amount} still fits",
    fgcoop: "FGCoop: {amount} still fits",
    sovereign: "Tesouro Nacional",
    empty: "No account or investment passes the filter yet.",
    alsoTitle: "Also evaluated",
    excludedLabel: "left out",
    indicators: "Yearly rates: CDI {cdi} · Selic {selic} · 12-month IPCA {ipca}",
    indicatorsMissing: "Central Bank indicators unavailable right now.",
    realYieldCaption: "real yield",
    footnote: "Real yield is after income tax and inflation. Poupança without TR.",
    reasons: {
      foreign_currency: "foreign currency, outside the totals",
      not_liquid: "not redeemable within 1 business day",
      liquidity_unknown: "liquidity unknown: confirm in Adjust",
      product_unknown: "product not recognised",
      not_covered: "no FGC and not Tesouro Selic",
      payment_institution_balance: "balance at a payment institution, no FGC",
      institution_unknown: "institution not identified: pick it in Adjust",
      fgc_limit_reached: "FGC limit reached for this holder",
      rate_unknown: "rate unknown",
      market_data_unavailable: "Central Bank indicators unavailable",
    },
  },
  markDialog: {
    title: "{account}",
    description: "What this household says about this account for the reserve.",
    reserveLabel: "Part of the reserve",
    liquidityLabel: "Redemption",
    liquidityOptions: {
      daily: "Within 1 business day",
      not_daily: "Later than 1 business day",
      unknown: "Don't know yet",
    },
    institutionLabel: "Issuing institution",
    institutionAuto: "Automatic: {institution}",
    institutionAutoUnknown: "Automatic: not identified",
    institutionUnlisted: "Another institution (not listed)",
    cancel: "Cancel",
    submit: "Save",
  },
  markSaved: "Reserve updated.",
  multipleUpdated: "Reserve multiple updated.",
  noticeDismissed: "Notice dismissed.",
  empty: {
    connectAction: "Connect bank",
    categorizeAction: "Go to transactions",
  },
  error: {
    message: "Couldn't load the reserve right now. Check your connection and try again.",
    retry: "Try again",
  },
  errors: {
    invalidInput: "Check the fields and try again.",
    failed: "Couldn't save right now. Try again.",
    noticeNotFound: "That notice is no longer available in this household.",
    notAllowed: "Only the household's owner or admin can change the reserve multiple.",
    accountNotFound: "That account is no longer in this household.",
  },
};

const ptBR = {
  overline: "Reserva",
  headline: {
    target: "Sua meta é {amount}.",
    estimate: "Sua meta estimada é {amount}.",
    noAccounts: "Conecte um banco para ver a meta da reserva da casa.",
    noHistory: "Categorize pelo menos um mês de gastos para ver a meta da reserva.",
  },
  multipleSelect: {
    label: "Meses de reserva",
    readOnly: "{multiple} meses",
  },
  tiles: {
    target: "Meta da reserva",
    targetMeta: "{multiple} meses de custo fixo",
    averageFixedCost: "Custo fixo médio",
    averageFixedCostFull: "média de 6 meses",
    averageFixedCostPartial: "média de: {months}",
    averageFixedCostEstimate: "estimativa com base em: {months}",
    currentReserve: "Reserva atual",
    currentReserveMeta: "Aparece quando uma conta for marcada como parte da reserva.",
    currentReserveCount: "{count} contas na reserva",
    currentReserveOne: "1 conta na reserva",
    coverage: "Cobertura",
    coverageMeta: "Vem das posições da reserva, quando houver alguma.",
    coverageMonths: "{months} meses de custo fixo",
  },
  monthlyTable: {
    title: "Custo fixo por mês",
    month: "Mês",
    amount: "Custo fixo",
    gap: "sem transações categorizadas",
  },
  notice: {
    message: "A meta da reserva mudou de {from} para {to} no fechamento de {month}.",
    action: "Entendi",
  },
  noticeBanner: {
    action: "Ver reserva",
  },
  coverage: {
    title: "Cobertura",
    summary: "{current} de {target}",
    months: "{months} meses de custo fixo",
    progressLabel: "Quanto da meta da reserva está coberto",
    empty: "Marque as contas que fazem parte da reserva para ver até onde ela vai.",
  },
  positions: {
    title: "Contas e investimentos",
    meta: "marque o que faz parte da reserva",
    account: "Conta",
    balance: "Saldo",
    liquidity: "Liquidez",
    tax: "IR",
    realYield: "Rendimento real",
    reserve: "Reserva",
    inReserve: "faz parte",
    notInReserve: "—",
    adjust: "Ajustar",
    adjustFor: "Ajustar {account}",
    advice: {
      suggest: "líquida e protegida, pode fazer parte da reserva",
      not_liquid: "está na reserva, mas não resgata em até 1 dia útil",
      liquidity_unknown: "está na reserva, liquidez desconhecida: confirme",
    },
    empty: "Nenhuma conta ou investimento pode guardar a reserva ainda.",
  },
  liquidity: {
    daily: "até D+1",
    not_daily: "acima de D+1",
    unknown: "confirme",
  },
  tax: {
    bracket: "{rate}",
    acquisitionDateUnknown: "{rate}, data de aplicação desconhecida",
    exempt: "isento",
    none: "—",
  },
  yield: {
    perYear: "{rate} a.a.",
    unknown: "—",
  },
  ranking: {
    title: "Onde colocar os próximos reais",
    meta: "resgate em até 1 dia útil e protegido, pelo rendimento real líquido",
    place: "{place}º",
    netYield: "{rate} a.a. depois do IR",
    fgc: "FGC: ainda cabem {amount}",
    fgcoop: "FGCoop: ainda cabem {amount}",
    sovereign: "Tesouro Nacional",
    empty: "Nenhuma conta ou investimento passa pelo filtro ainda.",
    alsoTitle: "Também avaliados",
    excludedLabel: "fora",
    indicators: "Taxas ao ano: CDI {cdi} · Selic {selic} · IPCA em 12 meses {ipca}",
    indicatorsMissing: "Indicadores do Banco Central indisponíveis no momento.",
    realYieldCaption: "rendimento real",
    footnote: "Rendimento real é o que sobra depois do IR e da inflação. Poupança sem TR.",
    reasons: {
      foreign_currency: "moeda estrangeira, fica fora dos totais",
      not_liquid: "não resgata em até 1 dia útil",
      liquidity_unknown: "liquidez desconhecida: confirme em Ajustar",
      product_unknown: "produto não reconhecido",
      not_covered: "sem FGC e não é Tesouro Selic",
      payment_institution_balance: "saldo em instituição de pagamento, sem FGC",
      institution_unknown: "instituição não identificada: escolha em Ajustar",
      fgc_limit_reached: "limite do FGC atingido para este titular",
      rate_unknown: "taxa desconhecida",
      market_data_unavailable: "indicadores do Banco Central indisponíveis",
    },
  },
  markDialog: {
    title: "{account}",
    description: "O que esta casa diz sobre esta conta para a reserva.",
    reserveLabel: "Faz parte da reserva",
    liquidityLabel: "Resgate",
    liquidityOptions: {
      daily: "Em até 1 dia útil",
      not_daily: "Em mais de 1 dia útil",
      unknown: "Ainda não sei",
    },
    institutionLabel: "Instituição emissora",
    institutionAuto: "Automático: {institution}",
    institutionAutoUnknown: "Automático: não identificada",
    institutionUnlisted: "Outra instituição (fora da lista)",
    cancel: "Cancelar",
    submit: "Salvar",
  },
  markSaved: "Reserva atualizada.",
  multipleUpdated: "Meses de reserva atualizados.",
  noticeDismissed: "Aviso dispensado.",
  empty: {
    connectAction: "Conectar banco",
    categorizeAction: "Ir para transações",
  },
  error: {
    message: "Não deu para carregar a reserva agora. Confira sua conexão e tente de novo.",
    retry: "Tentar de novo",
  },
  errors: {
    invalidInput: "Confira os campos e tente de novo.",
    failed: "Não deu para salvar agora. Tente de novo.",
    noticeNotFound: "Esse aviso não está mais disponível nesta casa.",
    notAllowed: "Só quem administra a casa (dono ou admin) pode alterar os meses de reserva.",
    accountNotFound: "Essa conta não está mais nesta casa.",
  },
} satisfies typeof en;

const reserveStrings = { en, ptBR };

export const t = reserveStrings.ptBR;
