export const authStrings = {
  en: {
    signUp: {
      title: "Create your account",
      subtitle: "Register to start managing your household's finances.",
      nameLabel: "Name",
      emailLabel: "Email",
      passwordLabel: "Password",
      termsLabel: "I accept the terms of use and the privacy policy",
      submit: "Create account",
      alreadyHaveAccount: "Already have an account?",
      signInLink: "Sign in",
    },
    signIn: {
      title: "Sign in",
      subtitle: "Enter your email and password to access your household.",
      emailLabel: "Email",
      passwordLabel: "Password",
      submit: "Sign in",
      noAccount: "Don't have an account yet?",
      signUpLink: "Create one",
    },
    verifyEmail: {
      title: "Confirm your email",
      body: "We sent a confirmation link to {email}. Click the link to activate your account.",
      resend: "Resend email",
      resent: "We sent the email again.",
    },
    overview: {
      title: "Overview",
      greeting: "Hello, {name}.",
      signOut: "Sign out",
    },
    errors: {
      invalidInput: "Check the fields highlighted below.",
      termsRequired: "You must accept the terms of use and the privacy policy.",
      registrationClosed: "Registration is closed at the moment.",
      inviteRequired: "Registration is invite-only at the moment.",
      signUpFailed: "We couldn't create your account. Try again.",
      invalidCredentials: "Incorrect email or password.",
      emailNotVerified: "Confirm your email before signing in.",
      resendFailed: "We couldn't resend the email. Try again.",
    },
  },
  ptBR: {
    signUp: {
      title: "Crie sua conta",
      subtitle: "Cadastre-se para começar a organizar as finanças da sua casa.",
      nameLabel: "Nome",
      emailLabel: "E-mail",
      passwordLabel: "Senha",
      termsLabel: "Aceito os termos de uso e a política de privacidade",
      submit: "Criar conta",
      alreadyHaveAccount: "Já tem uma conta?",
      signInLink: "Entrar",
    },
    signIn: {
      title: "Entrar",
      subtitle: "Informe seu e-mail e sua senha para acessar sua casa.",
      emailLabel: "E-mail",
      passwordLabel: "Senha",
      submit: "Entrar",
      noAccount: "Ainda não tem uma conta?",
      signUpLink: "Criar uma conta",
    },
    verifyEmail: {
      title: "Confirme seu e-mail",
      body: "Enviamos um link de confirmação para {email}. Clique no link para ativar sua conta.",
      resend: "Reenviar e-mail",
      resent: "Enviamos o e-mail novamente.",
    },
    overview: {
      title: "Visão geral",
      greeting: "Olá, {name}.",
      signOut: "Sair",
    },
    errors: {
      invalidInput: "Confira os campos destacados abaixo.",
      termsRequired: "Você precisa aceitar os termos de uso e a política de privacidade.",
      registrationClosed: "O cadastro está fechado no momento.",
      inviteRequired: "O cadastro é somente por convite no momento.",
      signUpFailed: "Não foi possível criar sua conta. Tente novamente.",
      invalidCredentials: "E-mail ou senha incorretos.",
      emailNotVerified: "Confirme seu e-mail antes de entrar.",
      resendFailed: "Não foi possível reenviar o e-mail. Tente novamente.",
    },
  },
} as const;
